# Generated by Django 5.0.2 on 2024-03-19 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppFinance', '0002_avatar_balance_cuenta_financial_report_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
